name: "formatter"
description: "docker image for tsfm"
author: "poifull10"

inputs:
  run-command: # id of input
    description: "Command to run"
    required: true
runs:
  using: "Docker"
  image: "unibeautify/clang-format"
  args:
    - ${{inputs.run-command}}

