name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: clang-debug
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: clang-debug
        uses: ./.github/actions/tsfm
        with:
          run-command: ".ci/build_clang_debug.sh"
