name: debug_release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release Build
        uses: ./.github/actions/tsfm
        with:
          run-command: ".ci/debug_release.sh"
