name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        uses: ./.github/actions/tsfm
        with:
          run-command: ".ci/release.sh"
